
const MI_LINK_FIJO="https://script.google.com/macros/s/AKfycbzdzPDp5m41vMn-OyGA8CxTFZHHLbH3V0LVN7HWp6VZi05UcSCnGj0N-uMAt4S_ApZC8Q/exec";
const DEFAULT_OWNER_KEY='d41c57e51278a5b41a496d2f';
const M=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
const K_DB='db_raum_v9',K_META='cajas_meta_v9',K_CFG='invoice_cfg_v2',K_TOMBS='raum_tombstones_v2',K_BACK='raum_auto_backup_v3',K_SESSION='raum_session_v1',K_USERS='raum_users_v1',K_ARCHIVED='raum_archived_boxes_v1';
const deviceId=localStorage.getItem('raum_device_id')||(()=>{const v='dev-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem('raum_device_id',v);return v})();
let db=[],cajasMetadata=[],tombstones=[],cajaActual=null,mesActual=new Date().getMonth(),modoResumen=false,deferredPrompt=null,currentUser=null,pendingInvoiceLogo=null;
const DEFAULT_INVOICE_CFG={business:'Raumauzi',taxId:'',phone:'5525 8033',address:'Guatemala',email:'',manager:'Tesorería',style:'bw1',format:'letter-landscape',title:'COMPROBANTE',footer:'Documento generado por Raumauzi PRO',logo:true,logoData:''};
let invoiceCfg={...DEFAULT_INVOICE_CFG};
function invoiceStorageKey(){return currentUser?`${K_CFG}_${currentUser.ownerKey}`:K_CFG}
function loadInvoiceSettingsForCurrentUser(){const key=invoiceStorageKey();let saved=JSON.parse(localStorage.getItem(key)||'null');invoiceCfg={...DEFAULT_INVOICE_CFG,...(saved||{})};if(saved)localStorage.setItem(key,JSON.stringify(invoiceCfg))}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function n(v){const x=parseFloat(v);return Number.isFinite(x)?x:0}function fMoney(v){return 'Q '+n(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function snapshot(){localStorage.setItem(K_BACK,JSON.stringify({date:new Date().toISOString(),db,cajasMetadata,tombstones,invoiceCfg}))}
function saveAll(){snapshot();localStorage.setItem(K_DB,JSON.stringify(db));localStorage.setItem(K_META,JSON.stringify(cajasMetadata));localStorage.setItem(K_TOMBS,JSON.stringify(tombstones));}
function migrate(){
 const readFirst=(keys,fallback=[])=>{for(const k of keys){try{const v=JSON.parse(localStorage.getItem(k)||'null');if(Array.isArray(v)&&v.length)return v}catch{}}return fallback};
 const oldDb=readFirst([K_DB,'db_raum_v8','db_raum_v7','db_raum_v6'],[]);
 const oldMeta=readFirst([K_META,'cajas_meta_v8','cajas_meta_v7','cajas_meta_v6'],[]);
 db=oldDb.map(x=>({...x,ownerKey:x.ownerKey||'legacy',updatedAt:x.updatedAt||Date.now(),deviceId:x.deviceId||deviceId,deleted:!!x.deleted}));
 cajasMetadata=oldMeta.map(x=>({...x,ownerKey:x.ownerKey||'legacy'}));
 tombstones=JSON.parse(localStorage.getItem(K_TOMBS)||'[]');
 saveAll();
}
function normBoxName(v){return String(v||'').trim().replace(/\s+/g,' ').toLocaleLowerCase('es')}
function boxIdentity(c){return `${normBoxName(c.nombre)}|${Number(c.year)||0}|${c.ownerKey||DEFAULT_OWNER_KEY}`}
function dedupeBoxes(list){const map=new Map();for(const raw of list||[]){if(!raw||!String(raw.nombre||'').trim())continue;const c={...raw,nombre:String(raw.nombre).trim().replace(/\s+/g,' '),year:Number(raw.year)||new Date().getFullYear(),saldoInicial:n(raw.saldoInicial)};const k=boxIdentity(c);const prev=map.get(k);if(!prev)map.set(k,c);else map.set(k,{...prev,...c,saldoInicial:Math.abs(n(c.saldoInicial))>=Math.abs(n(prev.saldoInicial))?n(c.saldoInicial):n(prev.saldoInicial)});}return [...map.values()]}
window.addEventListener('load',async()=>{migrate();generarAnios();actualizarFechas();setNetStatus();await initSecurity();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});
window.addEventListener('online',()=>{setNetStatus();fullSync(true)});window.addEventListener('offline',setNetStatus);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').classList.remove('hidden')});
async function triggerInstall(){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;return}const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);alert(isiOS?'En iPhone: toque Compartir y luego “Agregar a pantalla de inicio”.':'Abra el menú del navegador y elija “Instalar aplicación” o “Agregar a pantalla principal”.')}
function setNetStatus(sync=false){const c=document.getElementById('statusContainer');const t=document.getElementById('statusTxt');c.className='status '+(sync?'syncing':navigator.onLine?'online':'offline');t.textContent=sync?'Sincronizando…':navigator.onLine?'Online':'Sin conexión'}
function generarAnios(){const s=document.getElementById('selectYear');const selected=Number(s.value)||new Date().getFullYear();const found=[...cajasMetadata.map(c=>Number(c.year)),...db.map(x=>Number(x.cajaYear)),new Date().getFullYear()].filter(Number.isFinite);const min=Math.min(2025,...found),max=Math.max(new Date().getFullYear()+3,...found);s.innerHTML='';for(let i=min;i<=max;i++)s.add(new Option(i,i,i===selected,i===selected));if(![...s.options].some(o=>Number(o.value)===selected))s.value=new Date().getFullYear()}
function permittedBox(c){if(!currentUser)return false;if(currentUser.username==='mauzi')return true;return (c.ownerKey||DEFAULT_OWNER_KEY)===currentUser.ownerKey}
function renderCajas(){if(!currentUser)return;cajasMetadata=dedupeBoxes(cajasMetadata);generarAnios();const year=+document.getElementById('selectYear').value;const archived=JSON.parse(localStorage.getItem(K_ARCHIVED)||'[]');const list=cajasMetadata.filter(c=>+c.year===year&&permittedBox(c)&&!archived.includes(boxIdentity(c))).sort((a,b)=>a.nombre.localeCompare(b.nombre,'es'));document.getElementById('cajasCount').textContent=list.length+' caja(s)';document.getElementById('gridCajas').innerHTML=list.map(c=>`<div class="caja-card" onclick="abrirCajaByKey('${encodeURIComponent(c.nombre)}',${c.year},'${esc(c.ownerKey||DEFAULT_OWNER_KEY)}')"><div class="icon">📦</div><strong>${esc(c.nombre)}</strong><span>${c.year}</span><button class="icon-btn" title="Ocultar esta caja de este dispositivo" style="position:absolute;right:5px;top:5px" onclick="event.stopPropagation();archiveBox('${encodeURIComponent(c.nombre)}',${c.year},'${esc(c.ownerKey||DEFAULT_OWNER_KEY)}')">✕</button></div>`).join('')||'<p>No hay cajas visibles en este año. Presione Sincronizar para traerlas desde Google.</p>'}
function archiveBox(name,year,ownerKey){const c=cajasMetadata.find(x=>normBoxName(x.nombre)===normBoxName(decodeURIComponent(name))&&+x.year===+year&&(x.ownerKey||DEFAULT_OWNER_KEY)===ownerKey);if(!c)return;if(!confirm(`¿Ocultar la caja "${c.nombre}" solamente en este dispositivo? No se borrará de Google Sheets.`))return;const a=JSON.parse(localStorage.getItem(K_ARCHIVED)||'[]');const k=boxIdentity(c);if(!a.includes(k))a.push(k);localStorage.setItem(K_ARCHIVED,JSON.stringify(a));renderCajas()}
function restoreArchivedBoxes(){localStorage.removeItem(K_ARCHIVED);renderCajas();alert('Las cajas ocultas volvieron a mostrarse. No se modificó Google Sheets.')}
function abrirCajaByKey(name,year,ownerKey){const decoded=decodeURIComponent(name);const c=cajasMetadata.find(x=>normBoxName(x.nombre)===normBoxName(decoded)&&+x.year===+year&&(x.ownerKey||DEFAULT_OWNER_KEY)===ownerKey)||cajasMetadata.find(x=>normBoxName(x.nombre)===normBoxName(decoded)&&+x.year===+year);if(c&&permittedBox(c))abrirCaja(c)}
function abrirCaja(c){if(!permittedBox(c))return alert('No tiene permiso para abrir esta caja.');cajaActual=c;modoResumen=false;document.getElementById('vistaPrincipal').classList.add('hidden');document.getElementById('interfazCaja').classList.remove('hidden');document.getElementById('cajaActivaTitulo').textContent=`${c.nombre} · ${c.year}`;document.getElementById('initBal').value=n(c.saldoInicial);document.getElementById('hojaContenido').classList.add('hidden');document.getElementById('btnVerHoja').textContent='👁 Ver movimientos y reporte';actualizarFechas();renderTabs();renderMovimientos()}
function cerrarCaja(){cajaActual=null;document.getElementById('vistaPrincipal').classList.remove('hidden');document.getElementById('interfazCaja').classList.add('hidden');renderCajas()}
function nuevaCaja(){if(!currentUser)return;const nombre=(prompt('Nombre de la nueva caja o ministerio:')||'').trim();if(!nombre)return;const year=+document.getElementById('selectYear').value;const ownerKey=currentUser.ownerKey,ownerName=currentUser.username;if(cajasMetadata.some(c=>normBoxName(c.nombre)===normBoxName(nombre)&&+c.year===year&&(c.ownerKey||DEFAULT_OWNER_KEY)===ownerKey))return alert('Ya existe una caja con ese nombre y año.');cajasMetadata.push({nombre,year,saldoInicial:0,ownerKey,ownerName,updatedAt:Date.now(),deviceId});saveAll();renderCajas();alert('Caja creada para esta cuenta.')}
function actualizarFechas(){const t=new Date().toISOString().slice(0,10);document.getElementById('inDate').value=t;document.getElementById('outDate').value=t}
function add(type){const p=type==='entrada'?'in':'out',date=document.getElementById(p+'Date').value,desc=document.getElementById(p+'Desc').value.trim(),amount=n(document.getElementById(p+'Monto').value);if(!date||!desc||amount<=0)return alert('Complete fecha, concepto y monto válido.');const item={id:Date.now()+Math.floor(Math.random()*1000),synced:false,type,date,desc,amount,cajaNombre:cajaActual.nombre,cajaYear:+cajaActual.year,mIdx:new Date(date+'T12:00:00').getMonth(),updatedAt:Date.now(),deviceId,ownerKey:cajaActual.ownerKey||'legacy',ownerName:cajaActual.ownerName||'',deleted:false};db.push(item);saveAll();document.getElementById(p+'Desc').value='';document.getElementById(p+'Monto').value='';renderMovimientos();if(navigator.onLine)syncToCloud(item)}
function saveInit(){const saldo=n(document.getElementById('initBal').value);const idx=cajasMetadata.findIndex(c=>c.nombre===cajaActual.nombre&&+c.year===+cajaActual.year);if(idx>=0){cajasMetadata[idx].saldoInicial=saldo;cajasMetadata[idx].updatedAt=Date.now();cajaActual=cajasMetadata[idx]}saveAll();if(navigator.onLine)fetch(MI_LINK_FIJO,{method:'POST',mode:'no-cors',body:JSON.stringify({action:'saveInit',cajaNombre:cloudBoxName(cajaActual),cajaYear:cajaActual.year,saldo})}).catch(()=>{});renderMovimientos()}
function mergeCloud(local,cloud){const map=new Map(local.map(x=>[String(x.id),x]));for(const c of cloud){const key=String(c.id);if(tombstones.some(t=>String(t.id)===key))continue;const l=map.get(key);if(!l||n(c.updatedAt)>n(l.updatedAt))map.set(key,{...l,...c,synced:true,deleted:false})}return [...map.values()]}
function cloudBoxName(obj){const owner=obj.ownerKey||DEFAULT_OWNER_KEY;return owner===DEFAULT_OWNER_KEY?obj.cajaNombre||obj.nombre:`U_${owner}__${obj.cajaNombre||obj.nombre}`}
function parseCloudBox(raw){const full=String(raw||'');const pos=full.lastIndexOf('-');const base=pos>0?full.slice(0,pos):full;const year=pos>0?parseInt(full.slice(pos+1)):new Date().getFullYear();const m=base.match(/^U_([a-f0-9]{24})__(.*)$/);return m?{nombre:m[2],year,ownerKey:m[1],ownerName:'Usuario'}:{nombre:base,year,ownerKey:DEFAULT_OWNER_KEY,ownerName:'mauzi'}}
async function fullSync(silent=false){if(!navigator.onLine||!currentUser)return;if(!silent)setLoader(true,'Sincronizando sin reemplazar datos…');setNetStatus(true);try{const res=await fetch(MI_LINK_FIJO+'?action=read&ts='+Date.now(),{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const data=await res.json();const cloudMeta=(data.cajas||[]).map(c=>({...parseCloudBox(c.name),saldoInicial:n(c.saldo)}));const merged=[...cajasMetadata];for(const cm of cloudMeta){const idx=merged.findIndex(l=>normBoxName(l.nombre)===normBoxName(cm.nombre)&&+l.year===+cm.year&&(l.ownerKey||DEFAULT_OWNER_KEY)===(cm.ownerKey||DEFAULT_OWNER_KEY));if(idx<0)merged.push(cm);else merged[idx]={...merged[idx],...cm,nombre:merged[idx].nombre||cm.nombre,saldoInicial:n(cm.saldoInicial)}}cajasMetadata=dedupeBoxes(merged);const cloudMoves=(data.movimientos||[]).map(d=>{const p=parseCloudBox(d.cajaFull);const date=String(d.date||'').split('T')[0];return{id:d.id,synced:true,type:d.type,date,desc:d.desc,amount:n(d.amount),cajaNombre:p.nombre,cajaYear:p.year,ownerKey:p.ownerKey,ownerName:p.ownerName,mIdx:new Date(date+'T12:00:00').getMonth(),updatedAt:n(d.updatedAt)||0,deleted:false}});db=mergeCloud(db,cloudMoves);saveAll();generarAnios();renderCajas();if(cajaActual)renderMovimientos();for(const item of db.filter(x=>!x.synced&&!x.deleted&&permittedBox({ownerKey:x.ownerKey})))await syncToCloud(item);if(!silent)alert(`✅ Sincronización completada. Se encontraron ${cajasMetadata.length} cajas sin borrar ni reemplazar las existentes.`)}catch(e){console.error(e);if(!silent)alert('No se pudo leer Google. La aplicación no borró ni reemplazó sus datos locales.')}finally{setNetStatus(false);setLoader(false)}}
async function syncToCloud(item){try{await fetch(MI_LINK_FIJO,{method:'POST',mode:'no-cors',body:JSON.stringify({...item,sheet:`${cloudBoxName(item)}-${item.cajaYear}`})});item.synced=true;item.updatedAt=Date.now();saveAll();if(cajaActual)renderMovimientos()}catch(e){item.synced=false;saveAll()}}
async function deleteItem(id){if(!confirm('¿Borrar este movimiento? Se conservará una marca para evitar que reaparezca.'))return;const item=db.find(x=>String(x.id)===String(id));if(!item)return;snapshot();item.deleted=true;item.updatedAt=Date.now();tombstones.push({id:item.id,deletedAt:Date.now(),caja:`${cloudBoxName(item)}-${item.cajaYear}`});saveAll();renderMovimientos();if(navigator.onLine)fetch(MI_LINK_FIJO,{method:'POST',mode:'no-cors',body:JSON.stringify({action:'delete',id:item.id,caja:`${cloudBoxName(item)}-${item.cajaYear}`})}).catch(()=>{})}
function editItem(id){const item=db.find(x=>String(x.id)===String(id));if(!item)return;const desc=prompt('Editar concepto:',item.desc);if(desc===null)return;const amount=prompt('Editar monto:',item.amount);if(amount===null||n(amount)<=0)return;item.desc=desc.trim();item.amount=n(amount);item.synced=false;item.updatedAt=Date.now();saveAll();renderMovimientos();if(navigator.onLine)syncToCloud(item)}
function visibleData(){return db.filter(x=>!x.deleted)}
function renderMovimientos(){if(!cajaActual)return;document.getElementById('vistaResumen').classList.add('hidden');document.getElementById('tablasContenedor').classList.remove('hidden');document.getElementById('monthHeader').textContent=M[mesActual];const start=getBal(mesActual);const mData=visibleData().filter(i=>i.cajaNombre===cajaActual.nombre&&+i.cajaYear===+cajaActual.year&&+i.mIdx===mesActual);let si=0,so=0;document.getElementById('tbIn').innerHTML=`<tr><td>✅</td><td>01</td><td>${mesActual===0?'Saldo inicial':'Saldo anterior'}</td><td class="money">${fMoney(start)}</td><td>—</td><td>—</td></tr>`+mData.filter(i=>i.type==='entrada').map(e=>{si+=n(e.amount);return rowHtml(e)}).join('');document.getElementById('tbOut').innerHTML=mData.filter(i=>i.type==='salida').map(e=>{so+=n(e.amount);return rowHtml(e)}).join('');document.getElementById('sumIn').textContent=fMoney(si);document.getElementById('sumOut').textContent=fMoney(so);const prox=start+si-so;document.getElementById('resOut').textContent=fMoney(so);document.getElementById('resBal').textContent=fMoney(prox);document.getElementById('resEq').textContent=fMoney(so+prox)}
function rowHtml(e){return `<tr><td title="${e.synced?'Sincronizado':'Pendiente'}">${e.synced?'☁️':'🕒'}</td><td>${esc(e.date.split('-')[2])}</td><td>${esc(e.desc)}</td><td class="money">${fMoney(e.amount)}</td><td><button class="icon-btn" onclick="generarPDF('${e.id}')" title="Generar factura">🧾</button></td><td><div class="row-actions"><button class="icon-btn" onclick="editItem('${e.id}')">✏️</button><button class="icon-btn" onclick="deleteItem('${e.id}')">🗑️</button></div></td></tr>`}
function getBal(idx){let b=n(cajaActual.saldoInicial);for(let i=0;i<idx;i++){const m=visibleData().filter(d=>d.cajaNombre===cajaActual.nombre&&+d.cajaYear===+cajaActual.year&&+d.mIdx===i);b+=m.filter(x=>x.type==='entrada').reduce((a,v)=>a+n(v.amount),0)-m.filter(x=>x.type==='salida').reduce((a,v)=>a+n(v.amount),0)}return b}
function toggleHoja(){const h=document.getElementById('hojaContenido'),btn=document.getElementById('btnVerHoja');h.classList.toggle('hidden');btn.textContent=h.classList.contains('hidden')?'👁 Ver movimientos y reporte':'🙈 Ocultar movimientos'}
function renderTabs(){document.getElementById('tabsMeses').innerHTML=M.map((m,i)=>`<button class="tab ${i===mesActual&&!modoResumen?'active':''}" onclick="selectMonth(${i})">${m.slice(0,3)}</button>`).join('')+`<button class="tab ${modoResumen?'active':''}" onclick="renderAnual()">RESUMEN</button>`}
function selectMonth(i){mesActual=i;modoResumen=false;renderTabs();renderMovimientos()}
function renderAnual(){modoResumen=true;renderTabs();document.getElementById('tablasContenedor').classList.add('hidden');document.getElementById('vistaResumen').classList.remove('hidden');let ti=0,to=0,run=n(cajaActual.saldoInicial);document.getElementById('bodyResumen').innerHTML=M.map((m,i)=>{const d=visibleData().filter(x=>x.cajaNombre===cajaActual.nombre&&+x.cajaYear===+cajaActual.year&&+x.mIdx===i),ei=d.filter(x=>x.type==='entrada').reduce((a,v)=>a+n(v.amount),0),eo=d.filter(x=>x.type==='salida').reduce((a,v)=>a+n(v.amount),0);run+=ei-eo;ti+=ei;to+=eo;return `<tr><td>${m}</td><td class="money">${fMoney(ei)}</td><td class="money">${fMoney(eo)}</td><td class="money">${fMoney(run)}</td></tr>`}).join('');document.getElementById('resAnualInit').textContent=fMoney(cajaActual.saldoInicial);document.getElementById('resAnualIn').textContent=fMoney(ti);document.getElementById('resAnualOut').textContent=fMoney(to);document.getElementById('resAnualFinal').textContent=fMoney(run)}
function cambiarPasswordCaja(){alert('La caja ya está protegida por la cuenta del usuario. Para cambiar acceso, cierre sesión y use otra contraseña de cuenta.')}
function openInvoiceSettings(){for(const [id,key] of [['cfgBusiness','business'],['cfgTaxId','taxId'],['cfgPhone','phone'],['cfgAddress','address'],['cfgEmail','email'],['cfgManager','manager'],['cfgStyle','style'],['cfgFormat','format'],['cfgTitle','title'],['cfgFooter','footer']])document.getElementById(id).value=invoiceCfg[key]||'';document.getElementById('cfgLogo').checked=invoiceCfg.logo!==false;pendingInvoiceLogo=invoiceCfg.logoData||'';document.getElementById('cfgLogoPreview').src=pendingInvoiceLogo||'logo.png';updateInvoicePreview();openModal('invoiceModal')}
function selectInvoiceLogo(event){const file=event.target.files&&event.target.files[0];if(!file)return;if(file.size>1500000)return alert('Seleccione una imagen menor de 1.5 MB.');const r=new FileReader();r.onload=()=>{pendingInvoiceLogo=r.result;document.getElementById('cfgLogoPreview').src=pendingInvoiceLogo;document.getElementById('cfgLogo').checked=true;updateInvoicePreview()};r.readAsDataURL(file)}
function useDefaultInvoiceLogo(){pendingInvoiceLogo='';document.getElementById('cfgLogoPreview').src='logo.png';document.getElementById('cfgLogo').checked=true;updateInvoicePreview()}
function saveInvoiceSettings(){if(!currentUser)return alert('Debe iniciar sesión.');invoiceCfg={business:cfgBusiness.value.trim(),taxId:cfgTaxId.value.trim(),phone:cfgPhone.value.trim(),address:cfgAddress.value.trim(),email:cfgEmail.value.trim(),manager:cfgManager.value.trim(),style:cfgStyle.value,format:cfgFormat.value,title:cfgTitle.value.trim()||'COMPROBANTE',footer:cfgFooter.value.trim(),logo:cfgLogo.checked,logoData:pendingInvoiceLogo||''};localStorage.setItem(invoiceStorageKey(),JSON.stringify(invoiceCfg));snapshot();closeModal('invoiceModal');alert('Diseño de factura guardado para esta cuenta.')}
function invoiceDraft(){return {business:document.getElementById('cfgBusiness').value||'Nombre de la iglesia',taxId:document.getElementById('cfgTaxId').value||'',phone:document.getElementById('cfgPhone').value||'',address:document.getElementById('cfgAddress').value||'',email:document.getElementById('cfgEmail').value||'',manager:document.getElementById('cfgManager').value||'Tesorería',style:document.getElementById('cfgStyle').value||'bw1',title:document.getElementById('cfgTitle').value||'RECIBO DE CAJA',footer:document.getElementById('cfgFooter').value||'Comprobante emitido por tesorería',logo:document.getElementById('cfgLogo').checked,logoData:pendingInvoiceLogo||''}}
function invoiceHtml(cfg,item){const style=String(cfg.style||'bw1').replace('bw','');const logoSrc=cfg.logo?(cfg.logoData||'logo.png'):'';const num=String(item&&item.id||1).slice(-8).padStart(8,'0');const date=item&&item.date||'01/01/2026';const caja=item&&item.cajaNombre||'Caja general';const tipo=item&&item.type?(item.type==='entrada'?'Entrada':'Salida'):'Entrada';const desc=item&&item.desc||'Descripción del movimiento';const amount=item?fMoney(item.amount):'Q 0.00';return `<div class="invoice-sheet style-${style}"><div class="inv-topline"></div><div class="inv-head">${logoSrc?`<img class="inv-logo" src="${logoSrc}" alt="Logo">`:'<div></div>'}<div><div class="inv-title">${esc(cfg.title||'RECIBO DE CAJA')}</div><div class="inv-business">${esc(cfg.business||'Nombre de la iglesia')}</div><div class="inv-sub">${esc(cfg.address||'Dirección')} ${cfg.phone?` · Tel. ${esc(cfg.phone)}`:''}${cfg.email?` · ${esc(cfg.email)}`:''}</div></div><div class="inv-no"><small>NÚMERO DE RECIBO</small><strong>${esc(num)}</strong></div></div><div class="inv-meta"><div><div class="inv-label">DATOS DEL EMISOR</div><div class="inv-lines"><b>${esc(cfg.business||'Nombre de la iglesia')}</b><br>${cfg.taxId?`NIT / ID: ${esc(cfg.taxId)}<br>`:''}${esc(cfg.address||'Dirección')}<br>${cfg.phone?`Teléfono: ${esc(cfg.phone)}<br>`:''}${cfg.email?esc(cfg.email):''}</div></div><div><div class="inv-label">INFORMACIÓN DEL MOVIMIENTO</div><div class="inv-lines"><b>Fecha:</b> ${esc(date)}<br><b>Caja:</b> ${esc(caja)}<br><b>Tipo:</b> ${esc(tipo)}<br><b>Responsable:</b> ${esc(cfg.manager||'Tesorería')}</div></div></div><table class="inv-table"><thead><tr><th>DESCRIPCIÓN / CONCEPTO</th><th>TOTAL</th></tr></thead><tbody><tr><td>${esc(desc)}</td><td>${esc(amount)}</td></tr></tbody></table><div class="inv-bottom"><div class="inv-footerbox"><b>OBSERVACIÓN</b><br>${esc(cfg.footer||'Comprobante emitido por tesorería')}<div class="inv-sign"><div>Firma del responsable</div><div>Sello / autorización</div></div></div><div class="inv-total"><span>TOTAL</span><strong>${esc(amount)}</strong></div></div></div>`}
function updateInvoicePreview(){document.getElementById('invoicePreview').innerHTML=invoiceHtml(invoiceDraft(),null)}
function openTools(){openModal('toolsModal')}function openModal(id){document.getElementById(id).classList.add('open')}function closeModal(id){document.getElementById(id).classList.remove('open')}
function setLoader(show,text='Procesando…'){document.getElementById('loader').classList.toggle('open',!!show);document.getElementById('loaderText').textContent=text}
function exportBackup(){const blob=new Blob([JSON.stringify({version:'9.0',exportedAt:new Date().toISOString(),db,cajasMetadata,tombstones,invoiceCfg},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Raumauzi_v9.0_Respaldo_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importBackup(ev){const file=ev.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.db)||!Array.isArray(x.cajasMetadata))throw Error();if(!confirm('Esto combinará el respaldo con los datos actuales. ¿Continuar?'))return;db=mergeCloud(db,x.db);for(const c of x.cajasMetadata){if(!cajasMetadata.some(a=>a.nombre===c.nombre&&+a.year===+c.year))cajasMetadata.push(c)}tombstones=[...tombstones,...(x.tombstones||[])];invoiceCfg={...invoiceCfg,...(x.invoiceCfg||{})};saveAll();localStorage.setItem(invoiceStorageKey(),JSON.stringify(invoiceCfg));renderCajas();alert('Respaldo restaurado y combinado para esta cuenta.')}catch{alert('El archivo no es un respaldo válido.')}};r.readAsText(file);ev.target.value=''}

async function hashText(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function normalizeUser(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,'')}
async function deriveOwnerKey(username,password){return (await hashText('RAUMAUZI|'+normalizeUser(username)+'|'+password)).slice(0,24)}
async function initSecurity(){const defaultKey=DEFAULT_OWNER_KEY;let users=JSON.parse(localStorage.getItem(K_USERS)||'[]');if(!users.some(u=>u.username==='mauzi'))users.push({username:'mauzi',ownerKey:defaultKey,createdAt:new Date().toISOString(),initial:true});localStorage.setItem(K_USERS,JSON.stringify(users));let changed=false;cajasMetadata=cajasMetadata.map(c=>{if(!c.ownerKey||c.ownerKey==='legacy'||c.ownerKey==='admin'){changed=true;return{...c,ownerKey:defaultKey,ownerName:'mauzi'}}return c});db=db.map(x=>{if(!x.ownerKey||x.ownerKey==='legacy'||x.ownerKey==='admin'){changed=true;return{...x,ownerKey:defaultKey,ownerName:'mauzi'}}return x});if(changed)saveAll();const saved=JSON.parse(sessionStorage.getItem(K_SESSION)||'null');if(saved&&saved.ownerKey){currentUser=saved;enterApp()}else showAuth()}
function showAuth(){document.getElementById('authScreen').style.display='flex';document.getElementById('mainApp').classList.add('auth-hidden')}
function enterApp(){loadInvoiceSettingsForCurrentUser();document.getElementById('authScreen').style.display='none';document.getElementById('mainApp').classList.remove('auth-hidden');document.getElementById('userChip').textContent='👤 '+currentUser.username;renderCajas();if(navigator.onLine)fullSync(true)}
async function createUserAccount(){const username=normalizeUser(authUsername.value),password=authPassword.value;if(username.length<3)return alert('El usuario debe tener al menos 3 caracteres.');if(password.length<5)return alert('La contraseña debe tener al menos 5 caracteres.');let users=JSON.parse(localStorage.getItem(K_USERS)||'[]');if(users.some(u=>u.username===username))return alert('Ese nombre de usuario ya existe en este dispositivo.');const ownerKey=await deriveOwnerKey(username,password);users.push({username,ownerKey,createdAt:new Date().toISOString()});localStorage.setItem(K_USERS,JSON.stringify(users));currentUser={role:'user',username,ownerKey};sessionStorage.setItem(K_SESSION,JSON.stringify(currentUser));enterApp();alert('Cuenta creada. Guarde bien el usuario y contraseña.')}
async function loginAccount(){const username=normalizeUser(authUsername.value),password=authPassword.value;if(!username||!password)return alert('Escriba usuario y contraseña.');const ownerKey=await deriveOwnerKey(username,password);const users=JSON.parse(localStorage.getItem(K_USERS)||'[]');const valid=users.some(u=>u.username===username&&u.ownerKey===ownerKey);if(!valid)return alert('Usuario o contraseña incorrectos.');currentUser={role:'user',username,ownerKey};sessionStorage.setItem(K_SESSION,JSON.stringify(currentUser));enterApp()}
function logoutAccount(){if(!confirm('¿Cerrar sesión?'))return;cajaActual=null;currentUser=null;invoiceCfg={...DEFAULT_INVOICE_CFG};sessionStorage.removeItem(K_SESSION);document.getElementById('interfazCaja').classList.add('hidden');document.getElementById('vistaPrincipal').classList.remove('hidden');authPassword.value='';showAuth()}
async function changeUserPassword(){if(!currentUser)return;const oldPass=prompt('Contraseña actual:');if(oldPass===null)return;const oldKey=await deriveOwnerKey(currentUser.username,oldPass);if(oldKey!==currentUser.ownerKey)return alert('La contraseña actual es incorrecta.');const next=prompt('Nueva contraseña (mínimo 5 caracteres):');if(!next||next.length<5)return alert('La nueva contraseña debe tener al menos 5 caracteres.');const confirmPass=prompt('Repita la nueva contraseña:');if(next!==confirmPass)return alert('Las contraseñas no coinciden.');const newKey=await deriveOwnerKey(currentUser.username,next);let users=JSON.parse(localStorage.getItem(K_USERS)||'[]');users=users.map(u=>u.username===currentUser.username?{...u,ownerKey:newKey,updatedAt:new Date().toISOString()}:u);localStorage.setItem(K_USERS,JSON.stringify(users));cajasMetadata=cajasMetadata.map(c=>c.ownerKey===oldKey?{...c,ownerKey:newKey,ownerName:currentUser.username}:c);db=db.map(x=>x.ownerKey===oldKey?{...x,ownerKey:newKey,ownerName:currentUser.username,synced:false,updatedAt:Date.now()}:x);const oldCfg=localStorage.getItem(`${K_CFG}_${oldKey}`);if(oldCfg){localStorage.setItem(`${K_CFG}_${newKey}`,oldCfg);localStorage.removeItem(`${K_CFG}_${oldKey}`)}currentUser={role:'user',username:currentUser.username,ownerKey:newKey};sessionStorage.setItem(K_SESSION,JSON.stringify(currentUser));saveAll();renderCajas();alert('Contraseña actualizada correctamente.')}

function pdfSpec(format){if(format==='letter-portrait')return{orientation:'portrait',unit:'mm',format:'letter'};if(format==='a4-portrait')return{orientation:'portrait',unit:'mm',format:'a4'};if(format==='a4-landscape')return{orientation:'landscape',unit:'mm',format:'a4'};if(format==='half-letter')return{orientation:'portrait',unit:'mm',format:[139.7,215.9]};return{orientation:'landscape',unit:'mm',format:'letter'}}
function loadLogoData(){return new Promise(resolve=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);resolve(c.toDataURL('image/png'))};img.onerror=()=>resolve(null);img.src=invoiceCfg.logoData||'logo.png'})}
async function generarPDF(id){const item=db.find(x=>String(x.id)===String(id)&&!x.deleted);if(!item)return;if(!window.jspdf||!window.html2canvas)return alert('Las librerías de PDF aún no cargaron. Conéctese a internet una vez y vuelva a intentar.');setLoader(true,'Generando factura idéntica a la vista previa…');let stage=null;try{const cfg={...invoiceCfg};stage=document.createElement('div');stage.style.cssText='position:fixed;left:-12000px;top:0;width:1020px;background:#fff;padding:20px;z-index:-1';stage.innerHTML=invoiceHtml(cfg,item);document.body.appendChild(stage);const sheet=stage.querySelector('.invoice-sheet');await Promise.all(Array.from(sheet.querySelectorAll('img')).map(img=>img.complete?Promise.resolve():new Promise(r=>{img.onload=img.onerror=r})));const canvas=await html2canvas(sheet,{scale:2.2,backgroundColor:'#ffffff',useCORS:true,logging:false});const {jsPDF}=window.jspdf;const doc=new jsPDF(pdfSpec(cfg.format));const W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight();const ratio=Math.min(W/canvas.width,H/canvas.height);const iw=canvas.width*ratio,ih=canvas.height*ratio;doc.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',(W-iw)/2,(H-ih)/2,iw,ih,'FAST');doc.save(`Recibo_${String(item.id).slice(-8)}.pdf`)}catch(e){console.error(e);alert('No se pudo generar el PDF. Verifique el logo seleccionado e inténtelo nuevamente.')}finally{if(stage)stage.remove();setLoader(false)}}
